# Generated by Django 6.0.1 on 2026-02-27 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
