# Generated by Django 6.0.1 on 2026-02-27 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_helper_trainingslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='helper',
            name='total_training_hours',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='trainingslot',
            name='duration_hours',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='trainingslot',
            name='max_participants',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='trainingslot',
            name='helper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_slots', to='services.helper'),
        ),
    ]
