# Generated by Django 6.0.1 on 2026-02-27 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_alter_booking_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingslot',
            name='helper',
        ),
        migrations.AddField(
            model_name='trainingslot',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='training_slots', to='services.helper'),
        ),
    ]
