# Generated by Django 5.2.14 on 2026-05-29 17:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_subscriptionplan_subscription_apikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='credits',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 6, 28, 17, 18, 43, 131833, tzinfo=datetime.timezone.utc)),
        ),
    ]
