# Generated by Django 5.2.14 on 2026-05-31 11:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0017_subscriptionplan_is_custom_pricing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 6, 30, 11, 30, 31, 223145, tzinfo=datetime.timezone.utc)),
        ),
    ]
