# Generated by Django 5.2.14 on 2026-05-31 12:08

import services.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0019_alter_subscription_expires_at_subscriptionrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='expires_at',
            field=models.DateTimeField(default=services.models.default_expiry),
        ),
    ]
