# Generated by Django 5.2.14 on 2026-06-03 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0021_alter_apikey_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apikey',
            name='subscription',
        ),
        migrations.AlterField(
            model_name='apikey',
            name='name',
            field=models.CharField(default='AISidekick API Key', max_length=100),
        ),
    ]
