# Generated by Django 5.2.14 on 2026-06-03 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0022_remove_apikey_subscription_alter_apikey_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='is_unlimited',
            field=models.BooleanField(default=False),
        ),
    ]
