# Generated by Django 5.2.14 on 2026-06-06 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0023_subscriptionplan_is_unlimited'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='product_code',
            field=models.CharField(default='TEMP', max_length=50),
        ),
    ]
