# Generated by Django 5.2.14 on 2026-06-06 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0024_subscriptionplan_product_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='product_code',
            field=models.CharField(default='TEMP', max_length=50, unique=True),
        ),
    ]
